# Develop override settings

url: http://localhost:4000

analytics:
  provider: "google-gtag"
  google:
    tracking_id          : "UA-131727130-1"

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
